# Generated by Django 5.2.7 on 2025-11-04 11:00

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=airport.models.airplane_image_file_path),
        ),
    ]
